name: "Data Pipeline"

on:
  workflow_dispatch:  # This event triggers the workflow manually

jobs:
  process-data:
    runs-on: ubuntu-latest # The runner environment (Ubuntu in this case You can replace it with self-hosted)

    steps:
      - name: Checkout the code from the branch
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Cache Python dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install -r requirements.txt


      - name: Cache Python dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-


      - name: Run unit tests
        run: pytest tests/data -v

      - name: Download sample data
        run: python download_data.py --source-path "s3://my-bucket/data" --destination-dir ${{ github.workspace }}/data --sample
        timeout-minutes: 10

      - name: Pre-process sample data
        run: preprocess.py --input-dir ${{ github.workspace }}/data --output-dir ${{ github.workspace }}/processed_data --sample
        timeout-minutes: 10

      - name: Download full data
        run: python download_data.py --source-path "s3://my-bucket/data" --destination-dir ${{ github.workspace }}/data

      - name: Pre-process full data
        run: preprocess.py --input-dir ${{ github.workspace }}/data --output-dir ${{ github.workspace }}/processed_data

      - name: Publish dataset statistics/alerts
        run: python publish_dataset_stats.py --input-dir ${{ github.workspace }}/processed_data --output-dir ${{ github.workspace }}/alerts

      
  