name: "ML training"

on:
  workflow_dispatch:  # This event triggers the workflow manually

jobs:

  train-model:
    runs-on: self-hosted  # The runner environment (Ubuntu in this case)

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4  

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Cache Python dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name:  Pre-process data
        run: preprocess.py

      - name: run the training script
        id: train-model
        run: bash run.sh

      - name: publish metrics
        run: echo "accuracy=" ${{ steps.train-model.outputs.accuracy }}
      
      - name: Upload metrics
        uses: actions/upload-artifact@v3
        with:
          name: model-metrics
          path: metrics
  
  print-metrics:
    runs-on: ubuntu-latest
    needs: [train-model]
    steps:
      - name: Download metrics
        uses: actions/download-artifact@v3
        with:
          name: model-metrics
          path: metrics

      - name: Print metrics
        run: cat metrics/metrics.json