name: "ML training"

on:
  workflow_dispatch:  # This event triggers the workflow manually

jobs:
  download_dataset:
    runs-on: ubuntu-latest  # The runner environment (Ubuntu in this case)

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4  # This action checks out the code from the repository

      - name: Download the dataset
        run: python download_dataset.py  # This command runs the download_dataset.py script
  
  train-model:
    runs-on: ubuntu-latest  # The runner environment (Ubuntu in this case)

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4  

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: run the training script
        run: python train.py